In [9]:
import numpy as np
from enum import Enum
from typing import List
import random
import math

# Things to do
- Initialize n agents, n/2 on each team (team A, B)
- start with 1 topic for opinions
- give uniform/normal dist of [-1, 0), (0, -1] for team A, B respectively
- set some tolerance threshold for if agents on opposing teams can work together
- make some payoff matrix with [0, 1] for probability of reproducing

In [25]:
class Team(Enum):
    A = 0
    B = 1

class Agent():
    def __init__(self, team, opinions):
        self.team: Team = team
        self.opinions: List = opinions
        self.probReproduce = None


In [26]:
TOLERANCE = 0.3
# [[(A, A), (A, B)]
#  [(B, A), (B, B)]]
UTILITY_MATRIX = [[1.0, 1.5],
                 [1.5, 1.0]]
def getUtility(agent1: Agent, agent2: Agent):
    return UTILITY_MATRIX[agent1.team.value][agent2.team.value]

In [47]:
numAgents = 10 # always even

def generateAgents(distribution: str) -> tuple[List[Agent], List[Agent]]:
    teamA = []
    teamB = []
    # [mean, std_dev, low bound, upper bound]
    teamADistribution = [-0.5, 0.2, -1, 0]
    teamBDistribution = [0.5, 0.2, 0, 1]

    if distribution == "normal":
        teamAOpinions = np.random.normal(teamADistribution[0], teamADistribution[1], numAgents//2)
        teamBOpinions = np.random.normal(teamBDistribution[0], teamBDistribution[1], numAgents//2)
    elif distribution == "uniform":
        teamAOpinions = np.random.uniform(teamADistribution[2], teamADistribution[3], numAgents//2)
        teamBOpinions = np.random.uniform(teamBDistribution[2], teamBDistribution[3], numAgents//2)

    print(teamAOpinions)
    print(teamBOpinions)
    for i in range(0, numAgents):
        if i < numAgents/2:
            # team A
            team = Team.A
            opinion = teamAOpinions[i]
            teamA.append(Agent(team, [opinion]))
        else:
            # team B
            team = Team.B
            opinion = teamBOpinions[i - numAgents//2]
            teamB.append(Agent(team, [opinion]))

    return teamA, teamB
        

In [50]:
teamA, teamB = generateAgents("normal")

[-0.84442045 -0.6356482  -0.50848185 -0.06218279 -0.25107434]
[0.22415082 0.60097152 0.56897688 0.85986595 0.77546953]


In [49]:
# teamA, teamB = generateAgents("uniform")

[-0.83609282 -0.22726885 -0.54174029 -0.62043974 -0.67466879]
[0.1348297  0.86076813 0.98992741 0.16557888 0.55971299]


In [ ]:
def simMain(teamA: List[Agent], teamB: List[Agent], numIterations: int):
    # combine both lists
    # shuffle the combined list
    # take pairs of agents from the combined list
    # if odd number the last agents just dies (maybe some other way to solve this)
    # check if agents can work together pair by pair - either same team auto yes, diff team check threshold, or both cases check threshold
    # if they can't then prob reproduce is 0
    # if they can then get prob reporduce from utility
    # calculate opinions of offspring
    pass